### ISSUE TITLE
ag-grid isn't only for angular

### ISSUE THREAD

**Issue by ferhatelmas** [FancyGrid/awesome-grid#14]
According to documentation, ag-grid means agnostic grid and supports angular 1 or 2, react, vue, etc. I think mentioning it under angular is misleading.

**Comment by MikeTatsky** [comment]
Improved

**Comment by ferhatelmas** [comment]
:+1: Looks much better. What about mentioning React ?

**Comment by MikeTatsky** [comment]
Done
