### ISSUE TITLE
Unclear Guidelines

### ISSUE THREAD

**Issue by Kizaemon** [FancyGrid/awesome-grid#39]
Please provide a hard criteria/guidelines for putting/rejecting items on your list.

A submission was rejected because of "product does not look as popular and suitable for any serious applications".

This is different form my observations and I wonder what is the measurement criteria/threshold for popularity and seriousness? Is there i there any certification needs to be passed? 

Please provide more details, so I can make a judgement before submitting.
I am not affiliated with the software vendor, I just find the framework very useful for table/grid-oriented applications.

I use the framework seriously/successfully in production for a public company, so I was have naively assumed this would be a good fit for your list (along with DevExpress, FlexGrid, etc).

I have read through the Contribution Guidelines and followed each item, but there was nothing about certification:

-     Search previous suggestions before making a new one, as yours may be a duplicate.
=> checked, there were no duplicates
-     Make sure the list is useful before submitting. That implies it has enough content and every item has a good succinct description.
=> I submitted a "succinct description".
-     Make an individual pull request for each suggestion.
=> Yes
-     Use title-casing (AP style).
=> Yes
-     Use the following format: [List Name](link)
=> Yes
-     Link additions should be added alphabetically to the relevant category.
=> Yes
-     New categories or improvements to the existing categorization are welcome.
=> Not necessary, the "Frameworks" section exists already.
-     Check your spelling and grammar.
=> Done
-     Make sure your text editor is set to remove trailing whitespace.
=> Checked
-     The pull request and commit should have a useful title.
=> Checked
-     The body of your commit message should contain a link to the repository.
=> Yes

Kindest Regards,
Kizaemon

**Comment by MikeTatsky** [comment]
This repo is about good grid in terms of "table" solutions on JavaScript.
The main is not about UI framework.
For example, is https://www.iviewui.com suitable here?
No, since their grid component is too simple solution.

About https://wisej.com
Where are samples that to make desition about grid level?
This one?
https://wisej.com/examples/
1 - The are not about grids in fact.
2 - They are not runnable by click.

 Doc.
Is this doc?
https://wisej.com/docs/2.1/html/Welcome.htm
It does not look as welcome to use and more over no information about
grids.

This repo is meant to be about good solutions with which people will be comfortable to work.
With respect to you and https://wisej.com, by overview https://wisej.com it does not
look like suitable to this repo.
It is not good to add all other UI products that are oriented on grids, have complex to run samples, not clear documentation.

**Comment by MikeTatsky** [comment]
If you think that we are wrong.
Than there is similar repo but only about charts.
https://github.com/zingchart/awesome-charting
Try to add your solution into that repo and you will be rejected too although https://wisej.com has some images about charts on site.

**Comment by Kizaemon** [comment]
Thank you for your explanation. I do not think you are wrong, just the criteria was not clear to me.

Now I understand that you are not looking for general tables-on-the-web solutions, but limited only to a  subset of pure Javascript awesome libraries.

This was not clear for me from beginnig, as you put DevExpress, Telerik, IgniteUI and Sencha into the Frameworks section, which was misleading for me. I worked with all of them, so I can compare the features.

I'm very much interested in tables on the web, therefore I would have seriously expected to see iviewui table solution on your list, as it is a feasible solution to put table/grid on the web.
https://www.iviewui.com/components/table-en

Through your list I have learned all about the other frameworks, which I did not know about.
This is very useful, thank you very much for your work.

**Comment by Kizaemon** [comment]
WiseJ has no native implementation of Charts.
What you see there is a wrapper over ChartJS.
http://demo.wisej.com/ChartJS
The wrapping is very powerful, as it allows seamless integration with the data layer. No plumbing is necessary. ChartJS does rendering and the data and the events are first-class citizens of my application.

WiseJ has a **native** implementation of a table grid
https://github.com/iceteagroup/wisej-examples/tree/2.0/UserPaintCells

WiseJ has a native implementation of a TreeGrid
https://github.com/iceteagroup/wisej-examples/tree/2.0/TreeGrid

Native allows a full control over the rendering aspects (e.g. virtual scroll, user-painted cells) and event handling.

Here are further real-world application examples, utilizing tables/grids.
http://madewithwisej.com/
